// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnLIYNPYsMorqhKIG7ZQsC9wvUCkjlWU',
    appId: '1:34964347847:web:378ec77949f87d53c997e2',
    messagingSenderId: '34964347847',
    projectId: 'farmacia-app-e60c1',
    authDomain: 'farmacia-app-e60c1.firebaseapp.com',
    storageBucket: 'farmacia-app-e60c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nmcLeoahIojIMZUwyaKvzwEJrgQrl_w',
    appId: '1:34964347847:android:6c307b686d3585b5c997e2',
    messagingSenderId: '34964347847',
    projectId: 'farmacia-app-e60c1',
    storageBucket: 'farmacia-app-e60c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0F4BdXSuS4MZnuwkfdjLis27qG7fpvc',
    appId: '1:34964347847:ios:abc40027a614653ec997e2',
    messagingSenderId: '34964347847',
    projectId: 'farmacia-app-e60c1',
    storageBucket: 'farmacia-app-e60c1.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaMoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0F4BdXSuS4MZnuwkfdjLis27qG7fpvc',
    appId: '1:34964347847:ios:abc40027a614653ec997e2',
    messagingSenderId: '34964347847',
    projectId: 'farmacia-app-e60c1',
    storageBucket: 'farmacia-app-e60c1.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaMoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjKIQgLaag02Cf0JJaqDvuVDm5zQcox1A',
    appId: '1:34964347847:web:dff62b9cfa2e2576c997e2',
    messagingSenderId: '34964347847',
    projectId: 'farmacia-app-e60c1',
    authDomain: 'farmacia-app-e60c1.firebaseapp.com',
    storageBucket: 'farmacia-app-e60c1.firebasestorage.app',
  );
}
